# Generated by Django 5.0.6 on 2024-07-25 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('nomina', 'Nómina y Salarios'), ('inversiones', 'Retorno de Inversiones'), ('proyectos', 'Ingresos de Proyectos y Emprendimiento'), ('otros', 'Otros Ingresos')], default='nomina', max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('necesidades', 'Necesidades Básicas'), ('ahorro', 'Ahorro e Inversión'), ('educacion', 'Formación y Educación'), ('ocio', 'Ocio y Entretenimiento'), ('donaciones', 'Donaciones'), ('proyectos', 'Proyectos y Emprendimiento')], default='necesidades', max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
