# Generated by Django 5.0.6 on 2024-07-26 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='spending',
            options={'ordering': ['date']},
        ),
    ]
