# Generated by Django 5.0.6 on 2024-07-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_alter_income_options_alter_spending_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spending',
            name='user',
        ),
    ]
