# Generated by Django 5.0.6 on 2024-07-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_remove_income_user_remove_spending_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('salary', 'Salary and Wages'), ('investments', 'Return on Investments'), ('projects', 'Project and Entrepreneurship Income'), ('other', 'Other Income')], default='salary', max_length=100),
        ),
        migrations.AlterField(
            model_name='spending',
            name='category',
            field=models.CharField(choices=[('basic_needs', 'Basic Needs'), ('saving', 'Saving and Investment'), ('education', 'Education'), ('leisure', 'Leisure and Entertainment'), ('donations', 'Donations'), ('projects', 'Projects and Entrepreneurship')], default='basic_needs', max_length=100),
        ),
    ]
