# Generated by Django 5.1 on 2024-08-13 05:16

import Dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_alter_income_category_alter_spending_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(validators=[Dashboard.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.FloatField(validators=[Dashboard.models.validate_positive]),
        ),
    ]
