# Generated by Django 5.0.6 on 2024-07-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0002_alter_usergoal_percentage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergoal',
            unique_together={('category',)},
        ),
        migrations.RemoveField(
            model_name='usergoal',
            name='user',
        ),
    ]
