# Generated by Django 5.0.6 on 2024-07-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0003_alter_usergoal_unique_together_remove_usergoal_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergoal',
            unique_together=set(),
        ),
    ]
