# Generated by Django 5.0.6 on 2024-07-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0004_alter_usergoal_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='category',
            field=models.CharField(choices=[('basic_needs', 'Basic Needs'), ('saving', 'Saving and Investment'), ('education', 'Education'), ('leisure', 'Leisure and Entertainment'), ('donations', 'Donations'), ('projects', 'Projects and Entrepreneurship')], max_length=20),
        ),
    ]
