# Generated by Django 5.0.6 on 2024-07-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_alter_monthlyanalytics_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyanalytics',
            unique_together={('year', 'month', 'category')},
        ),
        migrations.RemoveField(
            model_name='spendinggoal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='spendinggoal',
            name='user_goal',
        ),
        migrations.RemoveField(
            model_name='monthlyanalytics',
            name='user',
        ),
    ]
